// Mocks generated by Mockito 5.4.5 from annotations
// in muslim_habbit/test/features/quran/domain/usecases/archive_item_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:muslim_habbit/core/error/failures.dart' as _i5;
import 'package:muslim_habbit/features/quran/domain/entities/memorization_item.dart'
    as _i6;
import 'package:muslim_habbit/features/quran/domain/entities/memorization_preferences.dart'
    as _i8;
import 'package:muslim_habbit/features/quran/domain/entities/review_schedule.dart'
    as _i7;
import 'package:muslim_habbit/features/quran/domain/repositories/memorization_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MemorizationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemorizationRepository extends _i1.Mock
    implements _i3.MemorizationRepository {
  MockMemorizationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>
      getMemorizationItems() => (super.noSuchMethod(
            Invocation.method(
              #getMemorizationItems,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemorizationItem>>(
              this,
              Invocation.method(
                #getMemorizationItems,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>
      getMemorizationItemById(String? id) => (super.noSuchMethod(
            Invocation.method(
              #getMemorizationItemById,
              [id],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                    _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
              this,
              Invocation.method(
                #getMemorizationItemById,
                [id],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>
      createMemorizationItem(_i6.MemorizationItem? item) => (super.noSuchMethod(
            Invocation.method(
              #createMemorizationItem,
              [item],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                    _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
              this,
              Invocation.method(
                #createMemorizationItem,
                [item],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>
      updateMemorizationItem(_i6.MemorizationItem? item) => (super.noSuchMethod(
            Invocation.method(
              #updateMemorizationItem,
              [item],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                    _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
              this,
              Invocation.method(
                #updateMemorizationItem,
                [item],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMemorizationItem(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMemorizationItem,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteMemorizationItem,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewSchedule>>
      getDailyReviewSchedule() => (super.noSuchMethod(
            Invocation.method(
              #getDailyReviewSchedule,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewSchedule>>.value(
                    _FakeEither_0<_i5.Failure, _i7.ReviewSchedule>(
              this,
              Invocation.method(
                #getDailyReviewSchedule,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i7.ReviewSchedule>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>> markItemAsReviewed(
          String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemAsReviewed,
          [itemId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
          this,
          Invocation.method(
            #markItemAsReviewed,
            [itemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.MemorizationPreferences>>
      getPreferences() => (super.noSuchMethod(
            Invocation.method(
              #getPreferences,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i8.MemorizationPreferences>>.value(
                _FakeEither_0<_i5.Failure, _i8.MemorizationPreferences>(
              this,
              Invocation.method(
                #getPreferences,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, _i8.MemorizationPreferences>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i8.MemorizationPreferences>> updatePreferences(
          _i8.MemorizationPreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferences,
          [preferences],
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, _i8.MemorizationPreferences>>.value(
            _FakeEither_0<_i5.Failure, _i8.MemorizationPreferences>(
          this,
          Invocation.method(
            #updatePreferences,
            [preferences],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.MemorizationPreferences>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.MemorizationStatistics>>
      getMemorizationStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getMemorizationStatistics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, _i3.MemorizationStatistics>>.value(
                _FakeEither_0<_i5.Failure, _i3.MemorizationStatistics>(
              this,
              Invocation.method(
                #getMemorizationStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i3.MemorizationStatistics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.DetailedMemorizationStatistics>>
      getDetailedStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getDetailedStatistics,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        _i3.DetailedMemorizationStatistics>>.value(
                _FakeEither_0<_i5.Failure, _i3.DetailedMemorizationStatistics>(
              this,
              Invocation.method(
                #getDetailedStatistics,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, _i3.DetailedMemorizationStatistics>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>
      getItemsByStatus(_i6.MemorizationStatus? status) => (super.noSuchMethod(
            Invocation.method(
              #getItemsByStatus,
              [status],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemorizationItem>>(
              this,
              Invocation.method(
                #getItemsByStatus,
                [status],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>> archiveItem(
          String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveItem,
          [itemId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
          this,
          Invocation.method(
            #archiveItem,
            [itemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>> unarchiveItem(
          String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unarchiveItem,
          [itemId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
          this,
          Invocation.method(
            #unarchiveItem,
            [itemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>
      getOverdueItems() => (super.noSuchMethod(
            Invocation.method(
              #getOverdueItems,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemorizationItem>>(
              this,
              Invocation.method(
                #getOverdueItems,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>> resetItemProgress(
          String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetItemProgress,
          [itemId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>.value(
                _FakeEither_0<_i5.Failure, _i6.MemorizationItem>(
          this,
          Invocation.method(
            #resetItemProgress,
            [itemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.MemorizationItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>
      getItemsNeedingReview() => (super.noSuchMethod(
            Invocation.method(
              #getItemsNeedingReview,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemorizationItem>>(
              this,
              Invocation.method(
                #getItemsNeedingReview,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<DateTime>>> getItemReviewHistory(
          String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemReviewHistory,
          [itemId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<DateTime>>>.value(
            _FakeEither_0<_i5.Failure, List<DateTime>>(
          this,
          Invocation.method(
            #getItemReviewHistory,
            [itemId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<DateTime>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>
      getItemsBySurah(int? surahNumber) => (super.noSuchMethod(
            Invocation.method(
              #getItemsBySurah,
              [surahNumber],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemorizationItem>>(
              this,
              Invocation.method(
                #getItemsBySurah,
                [surahNumber],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>
      getItemsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getItemsByDateRange,
              [
                start,
                end,
              ],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.MemorizationItem>>(
              this,
              Invocation.method(
                #getItemsByDateRange,
                [
                  start,
                  end,
                ],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MemorizationItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.StreakStatistics>>
      getStreakStatistics() => (super.noSuchMethod(
            Invocation.method(
              #getStreakStatistics,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i3.StreakStatistics>>.value(
                    _FakeEither_0<_i5.Failure, _i3.StreakStatistics>(
              this,
              Invocation.method(
                #getStreakStatistics,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, _i3.StreakStatistics>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, _i3.ProgressStatistics>> getProgressStatistics(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgressStatistics,
          [
            start,
            end,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i3.ProgressStatistics>>.value(
                _FakeEither_0<_i5.Failure, _i3.ProgressStatistics>(
          this,
          Invocation.method(
            #getProgressStatistics,
            [
              start,
              end,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i3.ProgressStatistics>>);
}
