// import '../../features/quran/data/models/hizb_model.dart';

import 'package:muslim_habbit/features/quran/data/models/hizb_model.dart';

abstract class Constants {
  static const latitude = "latitude";
  static const longitude = "longitude";

  static const addressAr = "addressAr";
  static const addressEn = "addressEn";

  static const marker = "marker";

  static const lanID = "lanID";

  static const adsAr = "ads_Ar";
  static const adminAr = "admin_ar";
  static const adminEn = "admin_en";
  static const privacyAr = "privacy_Ar";
  static const privacyEn = "privacy_En";
  static const forWhoAr = "for_who_Ar";
  static const forWhoEn = "for_who_En";
  static const contactUs = "contact_us";
  static const earlyJumaaAr = "jouma_hadith_ar";
  static const earlyJumaaEn = "jouma_hadith_en";
  static const nightPrayerAr = "night_hadith_ar";
  static const nightPrayerEn = "night_hadith_en";
  static const azkarAr = "azkar";
  static const azkarEn = "azkarEN";
  static const jumaSunnin1Ar = "jouma_sunnin_1_Ar";
  static const jumaSunnin2Ar = "jouma_sunnin_2_Ar";
  static const jumaSunnin3Ar = "jouma_sunnin_3_Ar";
  static const jumaSunnin1En = "jouma_sunnin_1_En";
  static const jumaSunnin2En = "jouma_sunnin_2_En";
  static const jumaSunnin3En = "jouma_sunnin_3_En";

  static const notification = "notification";

  static const azkarMuslimJson = "assets/json/azkar.json";
  static const azkarDetailsJson = "assets/json/azkar_data.json";

  static const email = "sulaimanmf@gmail.com";

  static const repeatedNotification = "repeatedNotification";

  static const earlyJumaaID = [7, 8, 9, 10, 11];
  static const earlyJumaaBody = [
    "✨ في الساعة الأولى كمن قرّب بدنة، فاحرص على التبكير تنال الأجر العظيم 🤲",
    "✨ في الساعة الثانية كمن قرّب بقرة، فاحرص على التبكير تنال الأجر العظيم 🤲",
    "✨ في الساعة الثالثة كمن قرّب كبش أقرن، فاحرص على التبكير تنال الأجر العظيم 🤲",
    "✨ في الساعة الرابعة كمن قرّب دجاجة، فاحرص على التبكير تنال الأجر العظيم 🤲",
    "✨ في الساعة الخامسة كمن قرّب بيضة، فاحرص على التبكير تنال الأجر العظيم 🤲",
  ];

  static const prayerTimesID = [14, 15, 16, 17, 18, 19, 20, 21, 22, 23];
  static const prayerTimesTitle = [
    "🕌 حي على الصلاة - صلاة الفجر",
    "☀️ وقت صلاة الظهر",
    "🌅 صلاة العصر - لحظة هدوء",
    "🌆 صلاة المغرب - لحظة الغروب",
    "🌌 صلاة العشاء - ختام يومك",
    "🕌 حي على الصلاة - صلاة الفجر",
    "☀️ وقت صلاة الظهر",
    "🌅 صلاة العصر - لحظة هدوء",
    "🌆 صلاة المغرب - لحظة الغروب",
    "🌌 صلاة العشاء - ختام يومك",
  ];
  static const prayerTimesBody = [
    "✨ الصلاة خير من النوم، قم وتوضأ وابدأ يومك بالبركة 🌿",
    "🤲 جاء وقت الظهر، فرصة للراحة والتقرب إلى الله، لا تؤخر صلاتك ⏳",
    "🌤️ دخل وقت العصر، جدد نشاطك واستعن بالصلاة قبل انشغالك 🕰️",
    "🌙 الشمس غربت، حان وقت المغرب، صلِّ وابدأ ليلتك ببركة وخير 💙",
    "💫 قبل أن تنام، أتمّ يومك بالصلاة والدعاء، استشعر الطمأنينة 🤍",
    "✨ الصلاة خير من النوم، قم وتوضأ وابدأ يومك بالبركة 🌿",
    "🤲 جاء وقت الظهر، فرصة للراحة والتقرب إلى الله، لا تؤخر صلاتك ⏳",
    "🌤️ دخل وقت العصر، جدد نشاطك واستعن بالصلاة قبل انشغالك 🕰️",
    "🌙 الشمس غربت، حان وقت المغرب، صلِّ وابدأ ليلتك ببركة وخير 💙",
    "💫 قبل أن تنام، أتمّ يومك بالصلاة والدعاء، استشعر الطمأنينة 🤍",
  ];

  static const doaaBeforIqmaaID = [24, 25, 26, 27, 28, 29, 30, 31, 32, 33];
  static const doaaBeforIqmaaTitle = [
    "🕌 وقت استجابة الدعاء",
    "🕌 لحظة ذهبية للدعاء",
    "📿 اغتنم وقت الإجابة",
    "🌆 فرصة عظيمة للدعاء",
    "💫 باب السماء مفتوح الآن",
    "🕌 وقت استجابة الدعاء",
    "🕌 لحظة ذهبية للدعاء",
    "📿 اغتنم وقت الإجابة",
    "🌆 فرصة عظيمة للدعاء",
    "💫 باب السماء مفتوح الآن",
  ];
  static const doaaBeforIgmaaBody = [
    "🤲 بين الأذان والإقامة دعوة لا تُرد، ارفع يديك واسأل الله من فضله ✨",
    "✨ لا تنسَ الدعاء بين الأذان والإقامة، فقد وعد الله بالإجابة 🤲",
    "🕰️ دقائق معدودة قبل الإقامة، استغلها بالدعاء بخشوع 🤍",
    "🌙 دقائق بين الأذان والإقامة هي كنز مخفي، لا تضيعها في الغفلة! 🤲",
    "✨ بين الأذان والإقامة وقت لا يُرد فيه الدعاء، اسأل الله حاجتك 🤲",
    "🤲 بين الأذان والإقامة دعوة لا تُرد، ارفع يديك واسأل الله من فضله ✨",
    "✨ لا تنسَ الدعاء بين الأذان والإقامة، فقد وعد الله بالإجابة 🤲",
    "🕰️ دقائق معدودة قبل الإقامة، استغلها بالدعاء بخشوع 🤍",
    "🌙 دقائق بين الأذان والإقامة هي كنز مخفي، لا تضيعها في الغفلة! 🤲",
    "✨ بين الأذان والإقامة وقت لا يُرد فيه الدعاء، اسأل الله حاجتك 🤲",
  ];

  static const nightPrayersID = [34, 35, 36, 37, 38, 39];
  static const nightPrayersTitle = [
    "🌙 الثلث الأول من الليل",
    "✨ الثلث الثاني من الليل",
    "🕋 الثلث الأخير من الليل",
    "🌙 الثلث الأول من الليل",
    "✨ الثلث الثاني من الليل",
    "🕋 الثلث الأخير من الليل",
  ];
  static const nightPrayersBody = [
    "✨ بدأ الليل، مناجاة الله في السكينة نور للقلب، قم ولو بركعتين 🤲",
    "💫 الآن وقت الصفوة، طهر قلبك بالصلاة، واملأ روحك بالسكينة 🕊️",
    "🌌 اقترب الفجر، وربك ينادي: هل من داعٍ فأستجيب له؟ لا تفوّت الدعاء 🤲",
    "✨ بدأ الليل، مناجاة الله في السكينة نور للقلب، قم ولو بركعتين 🤲",
    "💫 الآن وقت الصفوة، طهر قلبك بالصلاة، واملأ روحك بالسكينة 🕊️",
    "🌌 اقترب الفجر، وربك ينادي: هل من داعٍ فأستجيب له؟ لا تفوّت الدعاء 🤲",
  ];

  static const prayerOnPromptMohamedID = [40, 41, 42, 43, 44, 45, 46, 47];
  static const prayerOnPromptMohamedTime = [3, 6, 9, 12, 15, 18, 21, 23];

  static const quranList = [
    {
      "arName": "الفاتحة",
      "enName": "Al-Fatiha",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 7,
      "start": 1,
    },
    {
      "arName": "البقرة",
      "enName": "Al-Baqarah",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 286,
      "start": 2,
    },
    {
      "arName": "آل عمران",
      "enName": "Ali-Imran",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 200,
      "start": 50,
    },
    {
      "arName": "النساء",
      "enName": "An-Nisa",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 176,
      "start": 77,
    },
    {
      "arName": "المائدة",
      "enName": "Al-Maidah",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 120,
      "start": 106,
    },
    {
      "arName": "الأنعام",
      "enName": "Al-A’nam",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 165,
      "start": 128,
    },
    {
      "arName": "الأعراف",
      "enName": "Al-A’raf",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 206,
      "start": 151,
    },
    {
      "arName": "الأنفال",
      "enName": "Al-Anfal",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 75,
      "start": 177,
    },
    {
      "arName": "التوبة",
      "enName": "At-Tawbah",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 129,
      "start": 187,
    },
    {
      "arName": "يونس",
      "enName": "Yunus",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 109,
      "start": 208,
    },
    {
      "arName": "هود",
      "enName": "Hud",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 123,
      "start": 221,
    },
    {
      "arName": "يوسف",
      "enName": "Yusuf",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 111,
      "start": 235,
    },
    {
      "arName": "الرعد",
      "enName": "Ar-Ra'd",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 43,
      "start": 249,
    },
    {
      "arName": "ابراهيم",
      "enName": "Ibrahim",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 52,
      "start": 255,
    },
    {
      "arName": "الحجر",
      "enName": "Al-Hijr",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 99,
      "start": 262,
    },
    {
      "arName": "النحل",
      "enName": "An-Nahl",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 128,
      "start": 267,
    },
    {
      "arName": "الإسراء",
      "enName": "Al-Isra",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 111,
      "start": 282,
    },
    {
      "arName": "الكهف",
      "enName": "Al-Kahf",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 110,
      "start": 293,
    },
    {
      "arName": "مريم",
      "enName": "Maryam",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 98,
      "start": 305,
    },
    {
      "arName": "طه",
      "enName": "Taha",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 135,
      "start": 312,
    },
    {
      "arName": "الأنبياء",
      "enName": "Al-Anbiya",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 112,
      "start": 322,
    },
    {
      "arName": "الحج",
      "enName": "Al-Hajj",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 78,
      "start": 332,
    },
    {
      "arName": "المؤمنون",
      "enName": "Al-Mumenoon",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 118,
      "start": 342,
    },
    {
      "arName": "النور",
      "enName": "An-Noor",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 64,
      "start": 350,
    },
    {
      "arName": "الفرقان",
      "enName": "Al-Furqan",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 77,
      "start": 359,
    },
    {
      "arName": "الشعراء",
      "enName": "Ash-Shuara",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 227,
      "start": 367,
    },
    {
      "arName": "النمل",
      "enName": "An-Naml",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 93,
      "start": 377,
    },
    {
      "arName": "القصص",
      "enName": "Al-Qasas",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 88,
      "start": 385,
    },
    {
      "arName": "العنكبوت",
      "enName": "Al-Ankabut",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 69,
      "start": 396,
    },
    {
      "arName": "الروم",
      "enName": "Ar-Rum",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 60,
      "start": 404,
    },
    {
      "arName": "لقمان",
      "enName": "Luqman",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 34,
      "start": 411,
    },
    {
      "arName": "السجدة",
      "enName": "As-Sajda",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 30,
      "start": 415,
    },
    {
      "arName": "الأحزاب",
      "enName": "Al-Ahzab",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 73,
      "start": 418,
    },
    {
      "arName": "سبإ",
      "enName": "Saba",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 54,
      "start": 428,
    },
    {
      "arName": "فاطر",
      "enName": "Fatir",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 45,
      "start": 434,
    },
    {
      "arName": "يس",
      "enName": "Ya-Sin",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 83,
      "start": 440,
    },
    {
      "arName": "الصافات",
      "enName": "As-Saffat",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 182,
      "start": 446,
    },
    {
      "arName": "ص",
      "enName": "Sad",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 88,
      "start": 453,
    },
    {
      "arName": "الزمر",
      "enName": "Az-Zumar",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 75,
      "start": 458,
    },
    {
      "arName": "غافر",
      "enName": "Ghafir",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 85,
      "start": 467,
    },
    {
      "arName": "فصلت",
      "enName": "Fussilat",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 54,
      "start": 477,
    },
    {
      "arName": "الشورى",
      "enName": "Ash-Shura",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 53,
      "start": 483,
    },
    {
      "arName": "الزخرف",
      "enName": "Az-Zukhruf",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 89,
      "start": 489,
    },
    {
      "arName": "الدخان",
      "enName": "Ad-Dukhan",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 59,
      "start": 496,
    },
    {
      "arName": "الجاثية",
      "enName": "Al-Jathiya",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 37,
      "start": 499,
    },
    {
      "arName": "الأحقاف",
      "enName": "Al-Ahqaf",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 35,
      "start": 502,
    },
    {
      "arName": "محمد",
      "enName": "Muhammad",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 38,
      "start": 507,
    },
    {
      "arName": "الفتح",
      "enName": "Al-Fath",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 29,
      "start": 511,
    },
    {
      "arName": "الحجرات",
      "enName": "Al-Hujurat",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 18,
      "start": 515,
    },
    {
      "arName": "ق",
      "enName": "Qaf",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 45,
      "start": 518,
    },
    {
      "arName": "الذاريات",
      "enName": "Adh-Dhariyat",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 60,
      "start": 520,
    },
    {
      "arName": "الطور",
      "enName": "At-Tur",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 49,
      "start": 523,
    },
    {
      "arName": "النجم",
      "enName": "An-Najm",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 62,
      "start": 526,
    },
    {
      "arName": "القمر",
      "enName": "Al-Qamar",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 55,
      "start": 528,
    },
    {
      "arName": "الرحمن",
      "enName": "Ar-Rahman",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 78,
      "start": 531,
    },
    {
      "arName": "الواقعة",
      "enName": "Al-Waqia",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 96,
      "start": 534,
    },
    {
      "arName": "الحديد",
      "enName": "Al-Hadid",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 29,
      "start": 537,
    },
    {
      "arName": "المجادلة",
      "enName": "Al-Mujadila",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 22,
      "start": 542,
    },
    {
      "arName": "الحشر",
      "enName": "Al-Hashr",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 24,
      "start": 545,
    },
    {
      "arName": "الممتحنة",
      "enName": "Al-Mumtahina",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 13,
      "start": 549,
    },
    {
      "arName": "الصف",
      "enName": "As-Saff",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 14,
      "start": 551,
    },
    {
      "arName": "الجمعة",
      "enName": "Al-Jumua",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 11,
      "start": 553,
    },
    {
      "arName": "المنافقون",
      "enName": "Al-Munafiqoon",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 11,
      "start": 554,
    },
    {
      "arName": "التغابن",
      "enName": "At-Taghabun",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 18,
      "start": 556,
    },
    {
      "arName": "الطلاق",
      "enName": "At-Talaq",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 12,
      "start": 558,
    },
    {
      "arName": "التحريم",
      "enName": "At-Tahrim",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 12,
      "start": 560,
    },
    {
      "arName": "الملك",
      "enName": "Al-Mulk",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 30,
      "start": 562,
    },
    {
      "arName": "القلم",
      "enName": "Al-Qalam",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 52,
      "start": 564,
    },
    {
      "arName": "الحاقة",
      "enName": "Al-Haaqqa",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 52,
      "start": 566,
    },
    {
      "arName": "المعارج",
      "enName": "Al-Maarij",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 44,
      "start": 568,
    },
    {
      "arName": "نوح",
      "enName": "Nuh",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 28,
      "start": 570,
    },
    {
      "arName": "الجن",
      "enName": "Al-Jinn",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 28,
      "start": 572,
    },
    {
      "arName": "المزمل",
      "enName": "Al-Muzzammil",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 20,
      "start": 574,
    },
    {
      "arName": "المدثر",
      "enName": "Al-Muddathir",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 56,
      "start": 575,
    },
    {
      "arName": "القيامة",
      "enName": "Al-Qiyama",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 40,
      "start": 577,
    },
    {
      "arName": "الإنسان",
      "enName": "Al-Insan",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 31,
      "start": 578,
    },
    {
      "arName": "المرسلات",
      "enName": "Al-Mursalat",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 50,
      "start": 580,
    },
    {
      "arName": "النبأ",
      "enName": "An-Naba",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 40,
      "start": 582,
    },
    {
      "arName": "النازعات",
      "enName": "An-Nazi'at",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 46,
      "start": 583,
    },
    {
      "arName": "عبس",
      "enName": "Abasa",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 42,
      "start": 585,
    },
    {
      "arName": "التكوير",
      "enName": "At-Takwir",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 29,
      "start": 586,
    },
    {
      "arName": "الإنفطار",
      "enName": "Al-Infitar",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 19,
      "start": 587,
    },
    {
      "arName": "المطففين",
      "enName": "Al-Mutaffifin",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 36,
      "start": 587,
    },
    {
      "arName": "الإنشقاق",
      "enName": "Al-Inshiqaq",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 25,
      "start": 589,
    },
    {
      "arName": "البروج",
      "enName": "Al-Burooj",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 22,
      "start": 590,
    },
    {
      "arName": "الطارق",
      "enName": "At-Tariq",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 17,
      "start": 591,
    },
    {
      "arName": "الأعلى",
      "enName": "Al-Ala",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 19,
      "start": 591,
    },
    {
      "arName": "الغاشية",
      "enName": "Al-Ghashiya",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 26,
      "start": 592,
    },
    {
      "arName": "الفجر",
      "enName": "Al-Fajr",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 30,
      "start": 593,
    },
    {
      "arName": "البلد",
      "enName": "Al-Balad",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 20,
      "start": 594,
    },
    {
      "arName": "الشمس",
      "enName": "Ash-Shams",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 15,
      "start": 595,
    },
    {
      "arName": "الليل",
      "enName": "Al-Lail",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 21,
      "start": 595,
    },
    {
      "arName": "الضحى",
      "enName": "Ad-Duha",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 11,
      "start": 596,
    },
    {
      "arName": "الشرح",
      "enName": "Ash-Sharh",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 8,
      "start": 596,
    },
    {
      "arName": "التين",
      "enName": "At-Tin",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 8,
      "start": 597,
    },
    {
      "arName": "العلق",
      "enName": "Al-Alaq",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 19,
      "start": 597,
    },
    {
      "arName": "القدر",
      "enName": "Al-Qadr",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 5,
      "start": 598,
    },
    {
      "arName": "البينة",
      "enName": "Al-Bayyina",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 8,
      "start": 598,
    },
    {
      "arName": "الزلزلة",
      "enName": "Az-Zalzala",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 8,
      "start": 599,
    },
    {
      "arName": "العاديات",
      "enName": "Al-Adiyat",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 11,
      "start": 599,
    },
    {
      "arName": "القارعة",
      "enName": "Al-Qaria",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 11,
      "start": 600,
    },
    {
      "arName": "التكاثر",
      "enName": "At-Takathur",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 8,
      "start": 600,
    },
    {
      "arName": "العصر",
      "enName": "Al-Asr",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 3,
      "start": 601,
    },
    {
      "arName": "الهمزة",
      "enName": "Al-Humaza",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 9,
      "start": 601,
    },
    {
      "arName": "الفيل",
      "enName": "Al-Fil",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 5,
      "start": 601,
    },
    {
      "arName": "قريش",
      "enName": "Quraish",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 4,
      "start": 602,
    },
    {
      "arName": "الماعون",
      "enName": "Al-Maun",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 7,
      "start": 602,
    },
    {
      "arName": "الكوثر",
      "enName": "Al-Kawthar",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 3,
      "start": 602,
    },
    {
      "arName": "الكافرون",
      "enName": "Al-Kafiroon",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 6,
      "start": 603,
    },
    {
      "arName": "النصر",
      "enName": "An-Nasr",
      "arType": "مدنية",
      "enType": "Maddina",
      "verses": 3,
      "start": 603,
    },
    {
      "arName": "المسد",
      "enName": "Al-Masad",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 5,
      "start": 603,
    },
    {
      "arName": "الإخلاص",
      "enName": "Al-Ikhlas",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 4,
      "start": 604,
    },
    {
      "arName": "الفلق",
      "enName": "Al-Falaq",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 5,
      "start": 604,
    },
    {
      "arName": "الناس",
      "enName": "An-Nas",
      "arType": "مكية",
      "enType": "Meccan",
      "verses": 6,
      "start": 605,
    },
  ];
  static List<HizbModel> quranPages = [
    HizbModel(surah: 1, hizbQuarter: 1),
    HizbModel(surah: 2, hizbQuarter: 1),
    HizbModel(surah: 2, hizbQuarter: 1),
    HizbModel(surah: 2, hizbQuarter: 1),
    HizbModel(surah: 2, hizbQuarter: 2),
    HizbModel(surah: 2, hizbQuarter: 2),
    HizbModel(surah: 2, hizbQuarter: 3),
    HizbModel(surah: 2, hizbQuarter: 3),
    HizbModel(surah: 2, hizbQuarter: 4),
    HizbModel(surah: 2, hizbQuarter: 4),
    HizbModel(surah: 2, hizbQuarter: 5),
    HizbModel(surah: 2, hizbQuarter: 5),
    HizbModel(surah: 2, hizbQuarter: 5),
    HizbModel(surah: 2, hizbQuarter: 6),
    HizbModel(surah: 2, hizbQuarter: 6),
    HizbModel(surah: 2, hizbQuarter: 6),
    HizbModel(surah: 2, hizbQuarter: 7),
    HizbModel(surah: 2, hizbQuarter: 7),
    HizbModel(surah: 2, hizbQuarter: 8),
    HizbModel(surah: 2, hizbQuarter: 8),
    HizbModel(surah: 2, hizbQuarter: 8),
    HizbModel(surah: 2, hizbQuarter: 9),
    HizbModel(surah: 2, hizbQuarter: 9),
    HizbModel(surah: 2, hizbQuarter: 10),
    HizbModel(surah: 2, hizbQuarter: 10),
    HizbModel(surah: 2, hizbQuarter: 10),
    HizbModel(surah: 2, hizbQuarter: 11),
    HizbModel(surah: 2, hizbQuarter: 11),
    HizbModel(surah: 2, hizbQuarter: 12),
    HizbModel(surah: 2, hizbQuarter: 12),
    HizbModel(surah: 2, hizbQuarter: 12),
    HizbModel(surah: 2, hizbQuarter: 13),
    HizbModel(surah: 2, hizbQuarter: 13),
    HizbModel(surah: 2, hizbQuarter: 14),
    HizbModel(surah: 2, hizbQuarter: 14),
    HizbModel(surah: 2, hizbQuarter: 14),
    HizbModel(surah: 2, hizbQuarter: 15),
    HizbModel(surah: 2, hizbQuarter: 15),
    HizbModel(surah: 2, hizbQuarter: 16),
    HizbModel(surah: 2, hizbQuarter: 16),
    HizbModel(surah: 2, hizbQuarter: 16),
    HizbModel(surah: 2, hizbQuarter: 17),
    HizbModel(surah: 2, hizbQuarter: 17),
    HizbModel(surah: 2, hizbQuarter: 18),
    HizbModel(surah: 2, hizbQuarter: 18),
    HizbModel(surah: 2, hizbQuarter: 19),
    HizbModel(surah: 2, hizbQuarter: 19),
    HizbModel(surah: 2, hizbQuarter: 19),
    HizbModel(surah: 2, hizbQuarter: 20),
    HizbModel(surah: 3, hizbQuarter: 20),
    HizbModel(surah: 3, hizbQuarter: 21),
    HizbModel(surah: 3, hizbQuarter: 21),
    HizbModel(surah: 3, hizbQuarter: 21),
    HizbModel(surah: 3, hizbQuarter: 22),
    HizbModel(surah: 3, hizbQuarter: 22),
    HizbModel(surah: 3, hizbQuarter: 23),
    HizbModel(surah: 3, hizbQuarter: 23),
    HizbModel(surah: 3, hizbQuarter: 23),
    HizbModel(surah: 3, hizbQuarter: 24),
    HizbModel(surah: 3, hizbQuarter: 24),
    HizbModel(surah: 3, hizbQuarter: 24),
    HizbModel(surah: 3, hizbQuarter: 25),
    HizbModel(surah: 3, hizbQuarter: 25),
    HizbModel(surah: 3, hizbQuarter: 26),
    HizbModel(surah: 3, hizbQuarter: 26),
    HizbModel(surah: 3, hizbQuarter: 26),
    HizbModel(surah: 3, hizbQuarter: 27),
    HizbModel(surah: 3, hizbQuarter: 27),
    HizbModel(surah: 3, hizbQuarter: 28),
    HizbModel(surah: 3, hizbQuarter: 28),
    HizbModel(surah: 3, hizbQuarter: 28),
    HizbModel(surah: 3, hizbQuarter: 29),
    HizbModel(surah: 3, hizbQuarter: 29),
    HizbModel(surah: 3, hizbQuarter: 30),
    HizbModel(surah: 3, hizbQuarter: 30),
    HizbModel(surah: 3, hizbQuarter: 30),
    HizbModel(surah: 4, hizbQuarter: 31),
    HizbModel(surah: 4, hizbQuarter: 31),
    HizbModel(surah: 4, hizbQuarter: 32),
    HizbModel(surah: 4, hizbQuarter: 32),
    HizbModel(surah: 4, hizbQuarter: 32),
    HizbModel(surah: 4, hizbQuarter: 33),
    HizbModel(surah: 4, hizbQuarter: 33),
    HizbModel(surah: 4, hizbQuarter: 34),
    HizbModel(surah: 4, hizbQuarter: 34),
    HizbModel(surah: 4, hizbQuarter: 34),
    HizbModel(surah: 4, hizbQuarter: 35),
    HizbModel(surah: 4, hizbQuarter: 35),
    HizbModel(surah: 4, hizbQuarter: 36),
    HizbModel(surah: 4, hizbQuarter: 36),
    HizbModel(surah: 4, hizbQuarter: 36),
    HizbModel(surah: 4, hizbQuarter: 37),
    HizbModel(surah: 4, hizbQuarter: 37),
    HizbModel(surah: 4, hizbQuarter: 38),
    HizbModel(surah: 4, hizbQuarter: 38),
    HizbModel(surah: 4, hizbQuarter: 38),
    HizbModel(surah: 4, hizbQuarter: 39),
    HizbModel(surah: 4, hizbQuarter: 39),
    HizbModel(surah: 4, hizbQuarter: 39),
    HizbModel(surah: 4, hizbQuarter: 40),
    HizbModel(surah: 4, hizbQuarter: 40),
    HizbModel(surah: 4, hizbQuarter: 41),
    HizbModel(surah: 4, hizbQuarter: 41),
    HizbModel(surah: 4, hizbQuarter: 42),
    HizbModel(surah: 4, hizbQuarter: 42),
    HizbModel(surah: 4, hizbQuarter: 43),
    HizbModel(surah: 5, hizbQuarter: 43),
    HizbModel(surah: 5, hizbQuarter: 43),
    HizbModel(surah: 5, hizbQuarter: 44),
    HizbModel(surah: 5, hizbQuarter: 44),
    HizbModel(surah: 5, hizbQuarter: 44),
    HizbModel(surah: 5, hizbQuarter: 45),
    HizbModel(surah: 5, hizbQuarter: 45),
    HizbModel(surah: 5, hizbQuarter: 46),
    HizbModel(surah: 5, hizbQuarter: 46),
    HizbModel(surah: 5, hizbQuarter: 46),
    HizbModel(surah: 5, hizbQuarter: 47),
    HizbModel(surah: 5, hizbQuarter: 47),
    HizbModel(surah: 5, hizbQuarter: 48),
    HizbModel(surah: 5, hizbQuarter: 48),
    HizbModel(surah: 5, hizbQuarter: 49),
    HizbModel(surah: 5, hizbQuarter: 49),
    HizbModel(surah: 5, hizbQuarter: 49),
    HizbModel(surah: 5, hizbQuarter: 50),
    HizbModel(surah: 5, hizbQuarter: 50),
    HizbModel(surah: 5, hizbQuarter: 51),
    HizbModel(surah: 5, hizbQuarter: 51),
    HizbModel(surah: 6, hizbQuarter: 51),
    HizbModel(surah: 6, hizbQuarter: 52),
    HizbModel(surah: 6, hizbQuarter: 52),
    HizbModel(surah: 6, hizbQuarter: 52),
    HizbModel(surah: 6, hizbQuarter: 53),
    HizbModel(surah: 6, hizbQuarter: 53),
    HizbModel(surah: 6, hizbQuarter: 54),
    HizbModel(surah: 6, hizbQuarter: 54),
    HizbModel(surah: 6, hizbQuarter: 54),
    HizbModel(surah: 6, hizbQuarter: 55),
    HizbModel(surah: 6, hizbQuarter: 55),
    HizbModel(surah: 6, hizbQuarter: 55),
    HizbModel(surah: 6, hizbQuarter: 56),
    HizbModel(surah: 6, hizbQuarter: 56),
    HizbModel(surah: 6, hizbQuarter: 57),
    HizbModel(surah: 6, hizbQuarter: 57),
    HizbModel(surah: 6, hizbQuarter: 58),
    HizbModel(surah: 6, hizbQuarter: 58),
    HizbModel(surah: 6, hizbQuarter: 59),
    HizbModel(surah: 6, hizbQuarter: 59),
    HizbModel(surah: 6, hizbQuarter: 60),
    HizbModel(surah: 6, hizbQuarter: 60),
    HizbModel(surah: 6, hizbQuarter: 60),
    HizbModel(surah: 7, hizbQuarter: 61),
    HizbModel(surah: 7, hizbQuarter: 61),
    HizbModel(surah: 7, hizbQuarter: 61),
    HizbModel(surah: 7, hizbQuarter: 62),
    HizbModel(surah: 7, hizbQuarter: 62),
    HizbModel(surah: 7, hizbQuarter: 63),
    HizbModel(surah: 7, hizbQuarter: 63),
    HizbModel(surah: 7, hizbQuarter: 64),
    HizbModel(surah: 7, hizbQuarter: 64),
    HizbModel(surah: 7, hizbQuarter: 64),
    HizbModel(surah: 7, hizbQuarter: 64),
    HizbModel(surah: 7, hizbQuarter: 65),
    HizbModel(surah: 7, hizbQuarter: 65),
    HizbModel(surah: 7, hizbQuarter: 66),
    HizbModel(surah: 7, hizbQuarter: 66),
    HizbModel(surah: 7, hizbQuarter: 66),
    HizbModel(surah: 7, hizbQuarter: 67),
    HizbModel(surah: 7, hizbQuarter: 67),
    HizbModel(surah: 7, hizbQuarter: 67),
    HizbModel(surah: 7, hizbQuarter: 68),
    HizbModel(surah: 7, hizbQuarter: 68),
    HizbModel(surah: 7, hizbQuarter: 68),
    HizbModel(surah: 7, hizbQuarter: 69),
    HizbModel(surah: 7, hizbQuarter: 69),
    HizbModel(surah: 7, hizbQuarter: 70),
    HizbModel(surah: 7, hizbQuarter: 70),
    HizbModel(surah: 8, hizbQuarter: 71),
    HizbModel(surah: 8, hizbQuarter: 71),
    HizbModel(surah: 8, hizbQuarter: 72),
    HizbModel(surah: 8, hizbQuarter: 72),
    HizbModel(surah: 8, hizbQuarter: 72),
    HizbModel(surah: 8, hizbQuarter: 73),
    HizbModel(surah: 8, hizbQuarter: 73),
    HizbModel(surah: 8, hizbQuarter: 74),
    HizbModel(surah: 8, hizbQuarter: 74),
    HizbModel(surah: 8, hizbQuarter: 74),
    HizbModel(surah: 9, hizbQuarter: 75),
    HizbModel(surah: 9, hizbQuarter: 75),
    HizbModel(surah: 9, hizbQuarter: 76),
    HizbModel(surah: 9, hizbQuarter: 76),
    HizbModel(surah: 9, hizbQuarter: 76),
    HizbModel(surah: 9, hizbQuarter: 77),
    HizbModel(surah: 9, hizbQuarter: 77),
    HizbModel(surah: 9, hizbQuarter: 78),
    HizbModel(surah: 9, hizbQuarter: 78),
    HizbModel(surah: 9, hizbQuarter: 79),
    HizbModel(surah: 9, hizbQuarter: 79),
    HizbModel(surah: 9, hizbQuarter: 79),
    HizbModel(surah: 9, hizbQuarter: 80),
    HizbModel(surah: 9, hizbQuarter: 80),
    HizbModel(surah: 9, hizbQuarter: 81),
    HizbModel(surah: 9, hizbQuarter: 81),
    HizbModel(surah: 9, hizbQuarter: 81),
    HizbModel(surah: 9, hizbQuarter: 82),
    HizbModel(surah: 9, hizbQuarter: 82),
    HizbModel(surah: 9, hizbQuarter: 83),
    HizbModel(surah: 9, hizbQuarter: 83),
    HizbModel(surah: 10, hizbQuarter: 83),
    HizbModel(surah: 10, hizbQuarter: 84),
    HizbModel(surah: 10, hizbQuarter: 84),
    HizbModel(surah: 10, hizbQuarter: 84),
    HizbModel(surah: 10, hizbQuarter: 85),
    HizbModel(surah: 10, hizbQuarter: 85),
    HizbModel(surah: 10, hizbQuarter: 86),
    HizbModel(surah: 10, hizbQuarter: 86),
    HizbModel(surah: 10, hizbQuarter: 86),
    HizbModel(surah: 10, hizbQuarter: 87),
    HizbModel(surah: 10, hizbQuarter: 87),
    HizbModel(surah: 10, hizbQuarter: 88),
    HizbModel(surah: 10, hizbQuarter: 88),
    HizbModel(surah: 10, hizbQuarter: 88),
    HizbModel(surah: 11, hizbQuarter: 89),
    HizbModel(surah: 11, hizbQuarter: 89),
    HizbModel(surah: 11, hizbQuarter: 90),
    HizbModel(surah: 11, hizbQuarter: 90),
    HizbModel(surah: 11, hizbQuarter: 91),
    HizbModel(surah: 11, hizbQuarter: 91),
    HizbModel(surah: 11, hizbQuarter: 92),
    HizbModel(surah: 11, hizbQuarter: 92),
    HizbModel(surah: 11, hizbQuarter: 92),
    HizbModel(surah: 11, hizbQuarter: 93),
    HizbModel(surah: 11, hizbQuarter: 93),
    HizbModel(surah: 11, hizbQuarter: 94),
    HizbModel(surah: 11, hizbQuarter: 94),
    HizbModel(surah: 11, hizbQuarter: 94),
    HizbModel(surah: 12, hizbQuarter: 95),
    HizbModel(surah: 12, hizbQuarter: 95),
    HizbModel(surah: 12, hizbQuarter: 96),
    HizbModel(surah: 12, hizbQuarter: 96),
    HizbModel(surah: 12, hizbQuarter: 96),
    HizbModel(surah: 12, hizbQuarter: 96),
    HizbModel(surah: 12, hizbQuarter: 97),
    HizbModel(surah: 12, hizbQuarter: 97),
    HizbModel(surah: 12, hizbQuarter: 98),
    HizbModel(surah: 12, hizbQuarter: 98),
    HizbModel(surah: 12, hizbQuarter: 98),
    HizbModel(surah: 12, hizbQuarter: 99),
    HizbModel(surah: 12, hizbQuarter: 99),
    HizbModel(surah: 13, hizbQuarter: 100),
    HizbModel(surah: 13, hizbQuarter: 100),
    HizbModel(surah: 13, hizbQuarter: 100),
    HizbModel(surah: 13, hizbQuarter: 101),
    HizbModel(surah: 13, hizbQuarter: 101),
    HizbModel(surah: 13, hizbQuarter: 102),
    HizbModel(surah: 13, hizbQuarter: 102),
    HizbModel(surah: 14, hizbQuarter: 103),
    HizbModel(surah: 14, hizbQuarter: 103),
    HizbModel(surah: 14, hizbQuarter: 103),
    HizbModel(surah: 14, hizbQuarter: 104),
    HizbModel(surah: 14, hizbQuarter: 104),
    HizbModel(surah: 14, hizbQuarter: 104),
    HizbModel(surah: 15, hizbQuarter: 105),
    HizbModel(surah: 15, hizbQuarter: 105),
    HizbModel(surah: 15, hizbQuarter: 106),
    HizbModel(surah: 15, hizbQuarter: 106),
    HizbModel(surah: 15, hizbQuarter: 106),
    HizbModel(surah: 15, hizbQuarter: 107),
    HizbModel(surah: 16, hizbQuarter: 107),
    HizbModel(surah: 16, hizbQuarter: 107),
    HizbModel(surah: 16, hizbQuarter: 108),
    HizbModel(surah: 16, hizbQuarter: 108),
    HizbModel(surah: 16, hizbQuarter: 109),
    HizbModel(surah: 16, hizbQuarter: 109),
    HizbModel(surah: 16, hizbQuarter: 109),
    HizbModel(surah: 16, hizbQuarter: 110),
    HizbModel(surah: 16, hizbQuarter: 110),
    HizbModel(surah: 16, hizbQuarter: 111),
    HizbModel(surah: 16, hizbQuarter: 111),
    HizbModel(surah: 16, hizbQuarter: 111),
    HizbModel(surah: 16, hizbQuarter: 112),
    HizbModel(surah: 16, hizbQuarter: 112),
    HizbModel(surah: 17, hizbQuarter: 113),
    HizbModel(surah: 17, hizbQuarter: 113),
    HizbModel(surah: 17, hizbQuarter: 114),
    HizbModel(surah: 17, hizbQuarter: 114),
    HizbModel(surah: 17, hizbQuarter: 114),
    HizbModel(surah: 17, hizbQuarter: 115),
    HizbModel(surah: 17, hizbQuarter: 115),
    HizbModel(surah: 17, hizbQuarter: 116),
    HizbModel(surah: 17, hizbQuarter: 116),
    HizbModel(surah: 17, hizbQuarter: 116),
    HizbModel(surah: 17, hizbQuarter: 117),
    HizbModel(surah: 17, hizbQuarter: 117),
    HizbModel(surah: 18, hizbQuarter: 117),
    HizbModel(surah: 18, hizbQuarter: 118),
    HizbModel(surah: 18, hizbQuarter: 118),
    HizbModel(surah: 18, hizbQuarter: 119),
    HizbModel(surah: 18, hizbQuarter: 119),
    HizbModel(surah: 18, hizbQuarter: 120),
    HizbModel(surah: 18, hizbQuarter: 120),
    HizbModel(surah: 18, hizbQuarter: 120),
    HizbModel(surah: 18, hizbQuarter: 121),
    HizbModel(surah: 18, hizbQuarter: 121),
    HizbModel(surah: 18, hizbQuarter: 122),
    HizbModel(surah: 19, hizbQuarter: 122),
    HizbModel(surah: 19, hizbQuarter: 123),
    HizbModel(surah: 19, hizbQuarter: 123),
    HizbModel(surah: 19, hizbQuarter: 123),
    HizbModel(surah: 19, hizbQuarter: 124),
    HizbModel(surah: 19, hizbQuarter: 124),
    HizbModel(surah: 19, hizbQuarter: 124),
    HizbModel(surah: 19, hizbQuarter: 125),
    HizbModel(surah: 20, hizbQuarter: 125),
    HizbModel(surah: 20, hizbQuarter: 125),
    HizbModel(surah: 20, hizbQuarter: 126),
    HizbModel(surah: 20, hizbQuarter: 126),
    HizbModel(surah: 20, hizbQuarter: 127),
    HizbModel(surah: 20, hizbQuarter: 127),
    HizbModel(surah: 20, hizbQuarter: 128),
    HizbModel(surah: 20, hizbQuarter: 128),
    HizbModel(surah: 20, hizbQuarter: 128),
    HizbModel(surah: 21, hizbQuarter: 129),
    HizbModel(surah: 21, hizbQuarter: 129),
    HizbModel(surah: 21, hizbQuarter: 130),
    HizbModel(surah: 21, hizbQuarter: 130),
    HizbModel(surah: 21, hizbQuarter: 131),
    HizbModel(surah: 21, hizbQuarter: 131),
    HizbModel(surah: 21, hizbQuarter: 131),
    HizbModel(surah: 21, hizbQuarter: 132),
    HizbModel(surah: 21, hizbQuarter: 132),
    HizbModel(surah: 21, hizbQuarter: 132),
    HizbModel(surah: 22, hizbQuarter: 133),
    HizbModel(surah: 22, hizbQuarter: 133),
    HizbModel(surah: 22, hizbQuarter: 134),
    HizbModel(surah: 22, hizbQuarter: 134),
    HizbModel(surah: 22, hizbQuarter: 135),
    HizbModel(surah: 22, hizbQuarter: 135),
    HizbModel(surah: 22, hizbQuarter: 135),
    HizbModel(surah: 22, hizbQuarter: 136),
    HizbModel(surah: 22, hizbQuarter: 136),
    HizbModel(surah: 22, hizbQuarter: 136),
    HizbModel(surah: 23, hizbQuarter: 137),
    HizbModel(surah: 23, hizbQuarter: 137),
    HizbModel(surah: 23, hizbQuarter: 138),
    HizbModel(surah: 23, hizbQuarter: 138),
    HizbModel(surah: 23, hizbQuarter: 138),
    HizbModel(surah: 23, hizbQuarter: 139),
    HizbModel(surah: 23, hizbQuarter: 139),
    HizbModel(surah: 23, hizbQuarter: 139),
    HizbModel(surah: 24, hizbQuarter: 140),
    HizbModel(surah: 24, hizbQuarter: 140),
    HizbModel(surah: 24, hizbQuarter: 141),
    HizbModel(surah: 24, hizbQuarter: 141),
    HizbModel(surah: 24, hizbQuarter: 142),
    HizbModel(surah: 24, hizbQuarter: 142),
    HizbModel(surah: 24, hizbQuarter: 143),
    HizbModel(surah: 24, hizbQuarter: 143),
    HizbModel(surah: 24, hizbQuarter: 143),
    HizbModel(surah: 24, hizbQuarter: 144),
    HizbModel(surah: 25, hizbQuarter: 144),
    HizbModel(surah: 25, hizbQuarter: 144),
    HizbModel(surah: 25, hizbQuarter: 145),
    HizbModel(surah: 25, hizbQuarter: 145),
    HizbModel(surah: 25, hizbQuarter: 146),
    HizbModel(surah: 25, hizbQuarter: 146),
    HizbModel(surah: 25, hizbQuarter: 146),
    HizbModel(surah: 26, hizbQuarter: 147),
    HizbModel(surah: 26, hizbQuarter: 147),
    HizbModel(surah: 26, hizbQuarter: 148),
    HizbModel(surah: 26, hizbQuarter: 148),
    HizbModel(surah: 26, hizbQuarter: 149),
    HizbModel(surah: 26, hizbQuarter: 149),
    HizbModel(surah: 26, hizbQuarter: 149),
    HizbModel(surah: 26, hizbQuarter: 150),
    HizbModel(surah: 26, hizbQuarter: 150),
    HizbModel(surah: 26, hizbQuarter: 150),
    HizbModel(surah: 27, hizbQuarter: 151),
    HizbModel(surah: 27, hizbQuarter: 151),
    HizbModel(surah: 27, hizbQuarter: 152),
    HizbModel(surah: 27, hizbQuarter: 152),
    HizbModel(surah: 27, hizbQuarter: 152),
    HizbModel(surah: 27, hizbQuarter: 153),
    HizbModel(surah: 27, hizbQuarter: 153),
    HizbModel(surah: 27, hizbQuarter: 154),
    HizbModel(surah: 27, hizbQuarter: 154),
    HizbModel(surah: 28, hizbQuarter: 155),
    HizbModel(surah: 28, hizbQuarter: 155),
    HizbModel(surah: 28, hizbQuarter: 155),
    HizbModel(surah: 28, hizbQuarter: 156),
    HizbModel(surah: 28, hizbQuarter: 156),
    HizbModel(surah: 28, hizbQuarter: 156),
    HizbModel(surah: 28, hizbQuarter: 157),
    HizbModel(surah: 28, hizbQuarter: 157),
    HizbModel(surah: 28, hizbQuarter: 158),
    HizbModel(surah: 28, hizbQuarter: 158),
    HizbModel(surah: 28, hizbQuarter: 159),
    HizbModel(surah: 29, hizbQuarter: 159),
    HizbModel(surah: 29, hizbQuarter: 159),
    HizbModel(surah: 29, hizbQuarter: 160),
    HizbModel(surah: 29, hizbQuarter: 160),
    HizbModel(surah: 29, hizbQuarter: 160),
    HizbModel(surah: 29, hizbQuarter: 161),
    HizbModel(surah: 29, hizbQuarter: 161),
    HizbModel(surah: 29, hizbQuarter: 162),
    HizbModel(surah: 30, hizbQuarter: 162),
    HizbModel(surah: 30, hizbQuarter: 162),
    HizbModel(surah: 30, hizbQuarter: 163),
    HizbModel(surah: 30, hizbQuarter: 163),
    HizbModel(surah: 30, hizbQuarter: 163),
    HizbModel(surah: 30, hizbQuarter: 164),
    HizbModel(surah: 31, hizbQuarter: 164),
    HizbModel(surah: 31, hizbQuarter: 164),
    HizbModel(surah: 31, hizbQuarter: 165),
    HizbModel(surah: 31, hizbQuarter: 165),
    HizbModel(surah: 32, hizbQuarter: 166),
    HizbModel(surah: 32, hizbQuarter: 166),
    HizbModel(surah: 32, hizbQuarter: 166),
    HizbModel(surah: 33, hizbQuarter: 167),
    HizbModel(surah: 33, hizbQuarter: 167),
    HizbModel(surah: 33, hizbQuarter: 168),
    HizbModel(surah: 33, hizbQuarter: 168),
    HizbModel(surah: 33, hizbQuarter: 169),
    HizbModel(surah: 33, hizbQuarter: 169),
    HizbModel(surah: 33, hizbQuarter: 169),
    HizbModel(surah: 33, hizbQuarter: 170),
    HizbModel(surah: 33, hizbQuarter: 171),
    HizbModel(surah: 33, hizbQuarter: 171),
    HizbModel(surah: 34, hizbQuarter: 171),
    HizbModel(surah: 34, hizbQuarter: 172),
    HizbModel(surah: 34, hizbQuarter: 172),
    HizbModel(surah: 34, hizbQuarter: 173),
    HizbModel(surah: 34, hizbQuarter: 173),
    HizbModel(surah: 34, hizbQuarter: 174),
    HizbModel(surah: 34, hizbQuarter: 174),
    HizbModel(surah: 35, hizbQuarter: 174),
    HizbModel(surah: 35, hizbQuarter: 175),
    HizbModel(surah: 35, hizbQuarter: 175),
    HizbModel(surah: 35, hizbQuarter: 175),
    HizbModel(surah: 35, hizbQuarter: 176),
    HizbModel(surah: 35, hizbQuarter: 176),
    HizbModel(surah: 36, hizbQuarter: 176),
    HizbModel(surah: 36, hizbQuarter: 177),
    HizbModel(surah: 36, hizbQuarter: 177),
    HizbModel(surah: 36, hizbQuarter: 178),
    HizbModel(surah: 36, hizbQuarter: 178),
    HizbModel(surah: 37, hizbQuarter: 179),
    HizbModel(surah: 37, hizbQuarter: 179),
    HizbModel(surah: 37, hizbQuarter: 179),
    HizbModel(surah: 37, hizbQuarter: 180),
    HizbModel(surah: 37, hizbQuarter: 180),
    HizbModel(surah: 37, hizbQuarter: 181),
    HizbModel(surah: 37, hizbQuarter: 181),
    HizbModel(surah: 38, hizbQuarter: 181),
    HizbModel(surah: 38, hizbQuarter: 182),
    HizbModel(surah: 38, hizbQuarter: 182),
    HizbModel(surah: 38, hizbQuarter: 183),
    HizbModel(surah: 38, hizbQuarter: 183),
    HizbModel(surah: 38, hizbQuarter: 183),
    HizbModel(surah: 39, hizbQuarter: 184),
    HizbModel(surah: 39, hizbQuarter: 184),
    HizbModel(surah: 39, hizbQuarter: 184),
    HizbModel(surah: 39, hizbQuarter: 185),
    HizbModel(surah: 39, hizbQuarter: 185),
    HizbModel(surah: 39, hizbQuarter: 186),
    HizbModel(surah: 39, hizbQuarter: 186),
    HizbModel(surah: 39, hizbQuarter: 186),
    HizbModel(surah: 39, hizbQuarter: 187),
    HizbModel(surah: 40, hizbQuarter: 187),
    HizbModel(surah: 40, hizbQuarter: 188),
    HizbModel(surah: 40, hizbQuarter: 188),
    HizbModel(surah: 40, hizbQuarter: 188),
    HizbModel(surah: 40, hizbQuarter: 189),
    HizbModel(surah: 40, hizbQuarter: 189),
    HizbModel(surah: 40, hizbQuarter: 190),
    HizbModel(surah: 40, hizbQuarter: 190),
    HizbModel(surah: 40, hizbQuarter: 190),
    HizbModel(surah: 41, hizbQuarter: 191),
    HizbModel(surah: 41, hizbQuarter: 191),
    HizbModel(surah: 41, hizbQuarter: 192),
    HizbModel(surah: 41, hizbQuarter: 192),
    HizbModel(surah: 41, hizbQuarter: 192),
    HizbModel(surah: 41, hizbQuarter: 193),
    HizbModel(surah: 42, hizbQuarter: 193),
    HizbModel(surah: 42, hizbQuarter: 194),
    HizbModel(surah: 42, hizbQuarter: 194),
    HizbModel(surah: 42, hizbQuarter: 195),
    HizbModel(surah: 42, hizbQuarter: 195),
    HizbModel(surah: 42, hizbQuarter: 196),
    HizbModel(surah: 42, hizbQuarter: 196),
    HizbModel(surah: 43, hizbQuarter: 196),
    HizbModel(surah: 43, hizbQuarter: 197),
    HizbModel(surah: 43, hizbQuarter: 197),
    HizbModel(surah: 43, hizbQuarter: 198),
    HizbModel(surah: 43, hizbQuarter: 198),
    HizbModel(surah: 43, hizbQuarter: 198),
    HizbModel(surah: 44, hizbQuarter: 199),
    HizbModel(surah: 44, hizbQuarter: 199),
    HizbModel(surah: 44, hizbQuarter: 199),
    HizbModel(surah: 45, hizbQuarter: 200),
    HizbModel(surah: 45, hizbQuarter: 200),
    HizbModel(surah: 45, hizbQuarter: 200),
    HizbModel(surah: 45, hizbQuarter: 201),
    HizbModel(surah: 46, hizbQuarter: 201),
    HizbModel(surah: 46, hizbQuarter: 201),
    HizbModel(surah: 46, hizbQuarter: 202),
    HizbModel(surah: 46, hizbQuarter: 202),
    HizbModel(surah: 47, hizbQuarter: 203),
    HizbModel(surah: 47, hizbQuarter: 203),
    HizbModel(surah: 47, hizbQuarter: 203),
    HizbModel(surah: 47, hizbQuarter: 204),
    HizbModel(surah: 48, hizbQuarter: 204),
    HizbModel(surah: 48, hizbQuarter: 204),
    HizbModel(surah: 48, hizbQuarter: 205),
    HizbModel(surah: 48, hizbQuarter: 205),
    HizbModel(surah: 48, hizbQuarter: 206),
    HizbModel(surah: 49, hizbQuarter: 206),
    HizbModel(surah: 49, hizbQuarter: 207),
    HizbModel(surah: 50, hizbQuarter: 207),
    HizbModel(surah: 50, hizbQuarter: 208),
    HizbModel(surah: 50, hizbQuarter: 208),
    HizbModel(surah: 51, hizbQuarter: 208),
    HizbModel(surah: 51, hizbQuarter: 209),
    HizbModel(surah: 51, hizbQuarter: 209),
    HizbModel(surah: 52, hizbQuarter: 210),
    HizbModel(surah: 52, hizbQuarter: 210),
    HizbModel(surah: 53, hizbQuarter: 211),
    HizbModel(surah: 53, hizbQuarter: 211),
    HizbModel(surah: 53, hizbQuarter: 211),
    HizbModel(surah: 54, hizbQuarter: 212),
    HizbModel(surah: 54, hizbQuarter: 212),
    HizbModel(surah: 54, hizbQuarter: 213),
    HizbModel(surah: 55, hizbQuarter: 213),
    HizbModel(surah: 55, hizbQuarter: 213),
    HizbModel(surah: 55, hizbQuarter: 214),
    HizbModel(surah: 56, hizbQuarter: 214),
    HizbModel(surah: 56, hizbQuarter: 215),
    HizbModel(surah: 56, hizbQuarter: 215),
    HizbModel(surah: 57, hizbQuarter: 215),
    HizbModel(surah: 57, hizbQuarter: 216),
    HizbModel(surah: 57, hizbQuarter: 216),
    HizbModel(surah: 57, hizbQuarter: 216),
    HizbModel(surah: 58, hizbQuarter: 217),
    HizbModel(surah: 58, hizbQuarter: 217),
    HizbModel(surah: 58, hizbQuarter: 218),
    HizbModel(surah: 58, hizbQuarter: 218),
    HizbModel(surah: 59, hizbQuarter: 218),
    HizbModel(surah: 59, hizbQuarter: 219),
    HizbModel(surah: 59, hizbQuarter: 219),
    HizbModel(surah: 60, hizbQuarter: 219),
    HizbModel(surah: 60, hizbQuarter: 220),
    HizbModel(surah: 60, hizbQuarter: 220),
    HizbModel(surah: 61, hizbQuarter: 220),
    HizbModel(surah: 62, hizbQuarter: 221),
    HizbModel(surah: 62, hizbQuarter: 222),
    HizbModel(surah: 63, hizbQuarter: 222),
    HizbModel(surah: 64, hizbQuarter: 222),
    HizbModel(surah: 64, hizbQuarter: 222),
    HizbModel(surah: 65, hizbQuarter: 223),
    HizbModel(surah: 65, hizbQuarter: 223),
    HizbModel(surah: 66, hizbQuarter: 224),
    HizbModel(surah: 66, hizbQuarter: 224),
    HizbModel(surah: 67, hizbQuarter: 225),
    HizbModel(surah: 67, hizbQuarter: 225),
    HizbModel(surah: 67, hizbQuarter: 226),
    HizbModel(surah: 68, hizbQuarter: 226),
    HizbModel(surah: 68, hizbQuarter: 227),
    HizbModel(surah: 69, hizbQuarter: 227),
    HizbModel(surah: 69, hizbQuarter: 227),
    HizbModel(surah: 70, hizbQuarter: 228),
    HizbModel(surah: 70, hizbQuarter: 228),
    HizbModel(surah: 71, hizbQuarter: 228),
    HizbModel(surah: 72, hizbQuarter: 229),
    HizbModel(surah: 72, hizbQuarter: 229),
    HizbModel(surah: 73, hizbQuarter: 229),
    HizbModel(surah: 73, hizbQuarter: 230),
    HizbModel(surah: 74, hizbQuarter: 230),
    HizbModel(surah: 74, hizbQuarter: 231),
    HizbModel(surah: 75, hizbQuarter: 231),
    HizbModel(surah: 76, hizbQuarter: 232),
    HizbModel(surah: 76, hizbQuarter: 232),
    HizbModel(surah: 77, hizbQuarter: 232),
    HizbModel(surah: 78, hizbQuarter: 233),
    HizbModel(surah: 78, hizbQuarter: 233),
    HizbModel(surah: 79, hizbQuarter: 233),
    HizbModel(surah: 80, hizbQuarter: 234),
    HizbModel(surah: 81, hizbQuarter: 234),
    HizbModel(surah: 82, hizbQuarter: 235),
    HizbModel(surah: 83, hizbQuarter: 235),
    HizbModel(surah: 83, hizbQuarter: 236),
    HizbModel(surah: 85, hizbQuarter: 236),
    HizbModel(surah: 86, hizbQuarter: 237),
    HizbModel(surah: 87, hizbQuarter: 237),
    HizbModel(surah: 89, hizbQuarter: 237),
    HizbModel(surah: 89, hizbQuarter: 238),
    HizbModel(surah: 91, hizbQuarter: 238),
    HizbModel(surah: 92, hizbQuarter: 239),
    HizbModel(surah: 95, hizbQuarter: 239),
    HizbModel(surah: 97, hizbQuarter: 239),
    HizbModel(surah: 98, hizbQuarter: 240),
    HizbModel(surah: 100, hizbQuarter: 240),
    HizbModel(surah: 103, hizbQuarter: 240),
    HizbModel(surah: 106, hizbQuarter: 240),
    HizbModel(surah: 109, hizbQuarter: 240),
    HizbModel(surah: 112, hizbQuarter: 240),
  ];
}
