// Mocks generated by Mockito 5.4.5 from annotations
// in muslim_habbit/test/features/quran/data/services/memorization_migration_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:muslim_habbit/features/quran/data/datasources/memorization_local_data_source.dart'
    as _i8;
import 'package:muslim_habbit/features/quran/data/models/detailed_memorization_statistics_model.dart'
    as _i5;
import 'package:muslim_habbit/features/quran/data/models/memorization_item_model.dart'
    as _i2;
import 'package:muslim_habbit/features/quran/data/models/memorization_preferences_model.dart'
    as _i3;
import 'package:muslim_habbit/features/quran/data/models/memorization_statistics_model.dart'
    as _i4;
import 'package:muslim_habbit/features/quran/domain/entities/memorization_item.dart'
    as _i10;
import 'package:muslim_habbit/features/quran/domain/entities/progress_statistics.dart'
    as _i7;
import 'package:muslim_habbit/features/quran/domain/entities/streak_statistics.dart'
    as _i6;
import 'package:shared_preferences/shared_preferences.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMemorizationItemModel_0 extends _i1.SmartFake
    implements _i2.MemorizationItemModel {
  _FakeMemorizationItemModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemorizationPreferencesModel_1 extends _i1.SmartFake
    implements _i3.MemorizationPreferencesModel {
  _FakeMemorizationPreferencesModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemorizationStatisticsModel_2 extends _i1.SmartFake
    implements _i4.MemorizationStatisticsModel {
  _FakeMemorizationStatisticsModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDetailedMemorizationStatisticsModel_3 extends _i1.SmartFake
    implements _i5.DetailedMemorizationStatisticsModel {
  _FakeDetailedMemorizationStatisticsModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreakStatistics_4 extends _i1.SmartFake
    implements _i6.StreakStatistics {
  _FakeStreakStatistics_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProgressStatistics_5 extends _i1.SmartFake
    implements _i7.ProgressStatistics {
  _FakeProgressStatistics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MemorizationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemorizationLocalDataSource extends _i1.Mock
    implements _i8.MemorizationLocalDataSource {
  MockMemorizationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i2.MemorizationItemModel>> getMemorizationItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemorizationItems,
          [],
        ),
        returnValue: _i9.Future<List<_i2.MemorizationItemModel>>.value(
            <_i2.MemorizationItemModel>[]),
      ) as _i9.Future<List<_i2.MemorizationItemModel>>);

  @override
  _i9.Future<_i2.MemorizationItemModel> getMemorizationItemById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemorizationItemById,
          [id],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #getMemorizationItemById,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<_i2.MemorizationItemModel> createMemorizationItem(
          _i2.MemorizationItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMemorizationItem,
          [item],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #createMemorizationItem,
            [item],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<_i2.MemorizationItemModel> updateMemorizationItem(
          _i2.MemorizationItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMemorizationItem,
          [item],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #updateMemorizationItem,
            [item],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<void> deleteMemorizationItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMemorizationItem,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i2.MemorizationItemModel> markItemAsReviewed(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemAsReviewed,
          [itemId],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #markItemAsReviewed,
            [itemId],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<_i3.MemorizationPreferencesModel> getPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue: _i9.Future<_i3.MemorizationPreferencesModel>.value(
            _FakeMemorizationPreferencesModel_1(
          this,
          Invocation.method(
            #getPreferences,
            [],
          ),
        )),
      ) as _i9.Future<_i3.MemorizationPreferencesModel>);

  @override
  _i9.Future<_i3.MemorizationPreferencesModel> updatePreferences(
          _i3.MemorizationPreferencesModel? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreferences,
          [preferences],
        ),
        returnValue: _i9.Future<_i3.MemorizationPreferencesModel>.value(
            _FakeMemorizationPreferencesModel_1(
          this,
          Invocation.method(
            #updatePreferences,
            [preferences],
          ),
        )),
      ) as _i9.Future<_i3.MemorizationPreferencesModel>);

  @override
  _i9.Future<_i4.MemorizationStatisticsModel> getMemorizationStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMemorizationStatistics,
          [],
        ),
        returnValue: _i9.Future<_i4.MemorizationStatisticsModel>.value(
            _FakeMemorizationStatisticsModel_2(
          this,
          Invocation.method(
            #getMemorizationStatistics,
            [],
          ),
        )),
      ) as _i9.Future<_i4.MemorizationStatisticsModel>);

  @override
  _i9.Future<_i5.DetailedMemorizationStatisticsModel> getDetailedStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedStatistics,
          [],
        ),
        returnValue: _i9.Future<_i5.DetailedMemorizationStatisticsModel>.value(
            _FakeDetailedMemorizationStatisticsModel_3(
          this,
          Invocation.method(
            #getDetailedStatistics,
            [],
          ),
        )),
      ) as _i9.Future<_i5.DetailedMemorizationStatisticsModel>);

  @override
  _i9.Future<List<_i2.MemorizationItemModel>> getItemsByStatus(
          _i10.MemorizationStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByStatus,
          [status],
        ),
        returnValue: _i9.Future<List<_i2.MemorizationItemModel>>.value(
            <_i2.MemorizationItemModel>[]),
      ) as _i9.Future<List<_i2.MemorizationItemModel>>);

  @override
  _i9.Future<_i2.MemorizationItemModel> archiveItem(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #archiveItem,
          [itemId],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #archiveItem,
            [itemId],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<_i2.MemorizationItemModel> unarchiveItem(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #unarchiveItem,
          [itemId],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #unarchiveItem,
            [itemId],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<List<_i2.MemorizationItemModel>> getOverdueItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOverdueItems,
          [],
        ),
        returnValue: _i9.Future<List<_i2.MemorizationItemModel>>.value(
            <_i2.MemorizationItemModel>[]),
      ) as _i9.Future<List<_i2.MemorizationItemModel>>);

  @override
  _i9.Future<_i2.MemorizationItemModel> resetItemProgress(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetItemProgress,
          [itemId],
        ),
        returnValue: _i9.Future<_i2.MemorizationItemModel>.value(
            _FakeMemorizationItemModel_0(
          this,
          Invocation.method(
            #resetItemProgress,
            [itemId],
          ),
        )),
      ) as _i9.Future<_i2.MemorizationItemModel>);

  @override
  _i9.Future<List<_i2.MemorizationItemModel>> getItemsNeedingReview() =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsNeedingReview,
          [],
        ),
        returnValue: _i9.Future<List<_i2.MemorizationItemModel>>.value(
            <_i2.MemorizationItemModel>[]),
      ) as _i9.Future<List<_i2.MemorizationItemModel>>);

  @override
  _i9.Future<List<DateTime>> getItemReviewHistory(String? itemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemReviewHistory,
          [itemId],
        ),
        returnValue: _i9.Future<List<DateTime>>.value(<DateTime>[]),
      ) as _i9.Future<List<DateTime>>);

  @override
  _i9.Future<List<_i2.MemorizationItemModel>> getItemsBySurah(
          int? surahNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsBySurah,
          [surahNumber],
        ),
        returnValue: _i9.Future<List<_i2.MemorizationItemModel>>.value(
            <_i2.MemorizationItemModel>[]),
      ) as _i9.Future<List<_i2.MemorizationItemModel>>);

  @override
  _i9.Future<List<_i2.MemorizationItemModel>> getItemsByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i9.Future<List<_i2.MemorizationItemModel>>.value(
            <_i2.MemorizationItemModel>[]),
      ) as _i9.Future<List<_i2.MemorizationItemModel>>);

  @override
  _i9.Future<_i6.StreakStatistics> getStreakStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStreakStatistics,
          [],
        ),
        returnValue:
            _i9.Future<_i6.StreakStatistics>.value(_FakeStreakStatistics_4(
          this,
          Invocation.method(
            #getStreakStatistics,
            [],
          ),
        )),
      ) as _i9.Future<_i6.StreakStatistics>);

  @override
  _i9.Future<_i7.ProgressStatistics> getProgressStatistics(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProgressStatistics,
          [
            start,
            end,
          ],
        ),
        returnValue:
            _i9.Future<_i7.ProgressStatistics>.value(_FakeProgressStatistics_5(
          this,
          Invocation.method(
            #getProgressStatistics,
            [
              start,
              end,
            ],
          ),
        )),
      ) as _i9.Future<_i7.ProgressStatistics>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i11.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i9.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
