// Mocks generated by Mockito 5.4.5 from annotations
// in muslim_habbit/test/features/quran/data/services/quran_integration_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:flutter/gestures.dart' as _i7;
import 'package:flutter/material.dart' as _i3;
import 'package:get/get.dart' as _i4;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:quran_library/quran_library.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuranCtrl_0 extends _i1.SmartFake implements _i2.QuranCtrl {
  _FakeQuranCtrl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextStyle_1 extends _i1.SmartFake implements _i3.TextStyle {
  _FakeTextStyle_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeSurahNamesModel_2 extends _i1.SmartFake
    implements _i2.SurahNamesModel {
  _FakeSurahNamesModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_3 extends _i1.SmartFake implements _i3.Widget {
  _FakeWidget_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeSurahFontsModel_4 extends _i1.SmartFake
    implements _i2.SurahFontsModel {
  _FakeSurahFontsModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAyahFontsModel_5 extends _i1.SmartFake
    implements _i2.AyahFontsModel {
  _FakeAyahFontsModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxList_6<E> extends _i1.SmartFake implements _i4.RxList<E> {
  _FakeRxList_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxDouble_7 extends _i1.SmartFake implements _i4.RxDouble {
  _FakeRxDouble_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_8 extends _i1.SmartFake implements _i4.RxBool {
  _FakeRxBool_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuranState_9 extends _i1.SmartFake implements _i2.QuranState {
  _FakeQuranState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePageController_10 extends _i1.SmartFake
    implements _i3.PageController {
  _FakePageController_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_11<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [QuranLibrary].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranLibrary extends _i1.Mock implements _i2.QuranLibrary {
  MockQuranLibrary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuranCtrl get quranCtrl => (super.noSuchMethod(
        Invocation.getter(#quranCtrl),
        returnValue: _FakeQuranCtrl_0(
          this,
          Invocation.getter(#quranCtrl),
        ),
      ) as _i2.QuranCtrl);

  @override
  _i3.TextStyle get hafsStyle => (super.noSuchMethod(
        Invocation.getter(#hafsStyle),
        returnValue: _FakeTextStyle_1(
          this,
          Invocation.getter(#hafsStyle),
        ),
      ) as _i3.TextStyle);

  @override
  _i3.TextStyle get naskhStyle => (super.noSuchMethod(
        Invocation.getter(#naskhStyle),
        returnValue: _FakeTextStyle_1(
          this,
          Invocation.getter(#naskhStyle),
        ),
      ) as _i3.TextStyle);

  @override
  int get currentPageNumber => (super.noSuchMethod(
        Invocation.getter(#currentPageNumber),
        returnValue: 0,
      ) as int);

  @override
  List<String> get allJoz => (super.noSuchMethod(
        Invocation.getter(#allJoz),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get allHizb => (super.noSuchMethod(
        Invocation.getter(#allHizb),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i2.BookmarkModel> get allBookmarks => (super.noSuchMethod(
        Invocation.getter(#allBookmarks),
        returnValue: <_i2.BookmarkModel>[],
      ) as List<_i2.BookmarkModel>);

  @override
  List<_i2.BookmarkModel> get usedBookmarks => (super.noSuchMethod(
        Invocation.getter(#usedBookmarks),
        returnValue: <_i2.BookmarkModel>[],
      ) as List<_i2.BookmarkModel>);

  @override
  double get fontsDownloadProgress => (super.noSuchMethod(
        Invocation.getter(#fontsDownloadProgress),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isFontsDownloaded => (super.noSuchMethod(
        Invocation.getter(#isFontsDownloaded),
        returnValue: false,
      ) as bool);

  @override
  int get currentFontsSelected => (super.noSuchMethod(
        Invocation.getter(#currentFontsSelected),
        returnValue: 0,
      ) as int);

  @override
  set setFontsSelected(int? index) => super.noSuchMethod(
        Invocation.setter(
          #setFontsSelected,
          index,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.TafsirNameModel> get tafsirAndTraslationCollection =>
      (super.noSuchMethod(
        Invocation.getter(#tafsirAndTraslationCollection),
        returnValue: <_i2.TafsirNameModel>[],
      ) as List<_i2.TafsirNameModel>);

  @override
  List<_i2.TafsirTableData> get tafsirList => (super.noSuchMethod(
        Invocation.getter(#tafsirList),
        returnValue: <_i2.TafsirTableData>[],
      ) as List<_i2.TafsirTableData>);

  @override
  List<_i2.TranslationModel> get translationList => (super.noSuchMethod(
        Invocation.getter(#translationList),
        returnValue: <_i2.TranslationModel>[],
      ) as List<_i2.TranslationModel>);

  @override
  bool get isTafsir => (super.noSuchMethod(
        Invocation.getter(#isTafsir),
        returnValue: false,
      ) as bool);

  @override
  int get tafsirSelected => (super.noSuchMethod(
        Invocation.getter(#tafsirSelected),
        returnValue: 0,
      ) as int);

  @override
  _i5.Future<void> init({
    Map<int, List<_i2.BookmarkModel>>? userBookmarks,
    bool? overwriteBookmarks = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {
            #userBookmarks: userBookmarks,
            #overwriteBookmarks: overwriteBookmarks,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i2.AyahModel> search(String? text) => (super.noSuchMethod(
        Invocation.method(
          #search,
          [text],
        ),
        returnValue: <_i2.AyahModel>[],
      ) as List<_i2.AyahModel>);

  @override
  List<_i2.AyahModel> surahSearch(String? text) => (super.noSuchMethod(
        Invocation.method(
          #surahSearch,
          [text],
        ),
        returnValue: <_i2.AyahModel>[],
      ) as List<_i2.AyahModel>);

  @override
  void jumpToAyah(
    int? pageNumber,
    int? ayahUQNumber,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #jumpToAyah,
          [
            pageNumber,
            ayahUQNumber,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jumpToPage(int? page) => super.noSuchMethod(
        Invocation.method(
          #jumpToPage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jumpToJoz(int? jozz) => super.noSuchMethod(
        Invocation.method(
          #jumpToJoz,
          [jozz],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jumpToHizb(int? hizb) => super.noSuchMethod(
        Invocation.method(
          #jumpToHizb,
          [hizb],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jumpToBookmark(_i2.BookmarkModel? bookmark) => super.noSuchMethod(
        Invocation.method(
          #jumpToBookmark,
          [bookmark],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jumpToSurah(int? surah) => super.noSuchMethod(
        Invocation.method(
          #jumpToSurah,
          [surah],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<String> getAllSurahs({bool? isArabic = true}) => (super.noSuchMethod(
        Invocation.method(
          #getAllSurahs,
          [],
          {#isArabic: isArabic},
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getAllSurahsArtPath() => (super.noSuchMethod(
        Invocation.method(
          #getAllSurahsArtPath,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  void getSurahInfoDialog({
    required int? surahNumber,
    required _i3.BuildContext? context,
    _i2.SurahInfoStyle? surahInfoStyle,
    String? languageCode,
    bool? isDark = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getSurahInfoDialog,
          [],
          {
            #surahNumber: surahNumber,
            #context: context,
            #surahInfoStyle: surahInfoStyle,
            #languageCode: languageCode,
            #isDark: isDark,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.SurahNamesModel getSurahInfo({required int? surahNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSurahInfo,
          [],
          {#surahNumber: surahNumber},
        ),
        returnValue: _FakeSurahNamesModel_2(
          this,
          Invocation.method(
            #getSurahInfo,
            [],
            {#surahNumber: surahNumber},
          ),
        ),
      ) as _i2.SurahNamesModel);

  @override
  _i3.Widget getFontsDownloadDialog(
    _i2.DownloadFontsDialogStyle? downloadFontsDialogStyle,
    String? languageCode, {
    bool? isDark = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFontsDownloadDialog,
          [
            downloadFontsDialogStyle,
            languageCode,
          ],
          {#isDark: isDark},
        ),
        returnValue: _FakeWidget_3(
          this,
          Invocation.method(
            #getFontsDownloadDialog,
            [
              downloadFontsDialogStyle,
              languageCode,
            ],
            {#isDark: isDark},
          ),
        ),
      ) as _i3.Widget);

  @override
  _i3.Widget getFontsDownloadWidget(
    _i3.BuildContext? context, {
    _i2.DownloadFontsDialogStyle? downloadFontsDialogStyle,
    String? languageCode,
    bool? isDark = false,
    bool? isFontsLocal = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFontsDownloadWidget,
          [context],
          {
            #downloadFontsDialogStyle: downloadFontsDialogStyle,
            #languageCode: languageCode,
            #isDark: isDark,
            #isFontsLocal: isFontsLocal,
          },
        ),
        returnValue: _FakeWidget_3(
          this,
          Invocation.method(
            #getFontsDownloadWidget,
            [context],
            {
              #downloadFontsDialogStyle: downloadFontsDialogStyle,
              #languageCode: languageCode,
              #isDark: isDark,
              #isFontsLocal: isFontsLocal,
            },
          ),
        ),
      ) as _i3.Widget);

  @override
  void getFontsDownloadMethod({required int? fontIndex}) => super.noSuchMethod(
        Invocation.method(
          #getFontsDownloadMethod,
          [],
          {#fontIndex: fontIndex},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getFontsPrepareMethod({
    required int? pageIndex,
    bool? isFontsLocal = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #getFontsPrepareMethod,
          [],
          {
            #pageIndex: pageIndex,
            #isFontsLocal: isFontsLocal,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getDeleteFontsMethod() => super.noSuchMethod(
        Invocation.method(
          #getDeleteFontsMethod,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBookmark({
    required String? surahName,
    required int? ayahNumber,
    required int? ayahId,
    required int? page,
    required int? bookmarkId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setBookmark,
          [],
          {
            #surahName: surahName,
            #ayahNumber: ayahNumber,
            #ayahId: ayahId,
            #page: page,
            #bookmarkId: bookmarkId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeBookmark({required int? bookmarkId}) => super.noSuchMethod(
        Invocation.method(
          #removeBookmark,
          [],
          {#bookmarkId: bookmarkId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.SurahFontsModel> getAllSurahInPageByPageNumber(
          {required int? pageNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSurahInPageByPageNumber,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: <_i2.SurahFontsModel>[],
      ) as List<_i2.SurahFontsModel>);

  @override
  _i2.SurahFontsModel getCurrentSurahDataByPageNumber(
          {required int? pageNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSurahDataByPageNumber,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: _FakeSurahFontsModel_4(
          this,
          Invocation.method(
            #getCurrentSurahDataByPageNumber,
            [],
            {#pageNumber: pageNumber},
          ),
        ),
      ) as _i2.SurahFontsModel);

  @override
  _i2.SurahFontsModel getCurrentSurahDataByAyah(
          {required _i2.AyahFontsModel? ayah}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSurahDataByAyah,
          [],
          {#ayah: ayah},
        ),
        returnValue: _FakeSurahFontsModel_4(
          this,
          Invocation.method(
            #getCurrentSurahDataByAyah,
            [],
            {#ayah: ayah},
          ),
        ),
      ) as _i2.SurahFontsModel);

  @override
  _i2.SurahFontsModel getCurrentSurahDataByAyahUniqueNumber(
          {required int? ayahUniqueNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentSurahDataByAyahUniqueNumber,
          [],
          {#ayahUniqueNumber: ayahUniqueNumber},
        ),
        returnValue: _FakeSurahFontsModel_4(
          this,
          Invocation.method(
            #getCurrentSurahDataByAyahUniqueNumber,
            [],
            {#ayahUniqueNumber: ayahUniqueNumber},
          ),
        ),
      ) as _i2.SurahFontsModel);

  @override
  _i2.AyahFontsModel getJuzByPageNumber({required int? pageNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJuzByPageNumber,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: _FakeAyahFontsModel_5(
          this,
          Invocation.method(
            #getJuzByPageNumber,
            [],
            {#pageNumber: pageNumber},
          ),
        ),
      ) as _i2.AyahFontsModel);

  @override
  List<_i2.AyahFontsModel> getPageAyahsByPageNumber(
          {required int? pageNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPageAyahsByPageNumber,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: <_i2.AyahFontsModel>[],
      ) as List<_i2.AyahFontsModel>);

  @override
  _i5.Future<void> initTafsir() => (super.noSuchMethod(
        Invocation.method(
          #initTafsir,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.Widget changeTafsirPopupMenu(
    _i2.TafsirStyle? tafsirStyle, {
    int? pageNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeTafsirPopupMenu,
          [tafsirStyle],
          {#pageNumber: pageNumber},
        ),
        returnValue: _FakeWidget_3(
          this,
          Invocation.method(
            #changeTafsirPopupMenu,
            [tafsirStyle],
            {#pageNumber: pageNumber},
          ),
        ),
      ) as _i3.Widget);

  @override
  bool getTafsirDownloaded(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getTafsirDownloaded,
          [index],
        ),
        returnValue: false,
      ) as bool);

  @override
  void changeTafsirSwitch(
    int? index, {
    int? pageNumber,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #changeTafsirSwitch,
          [index],
          {#pageNumber: pageNumber},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> fetchTranslation() => (super.noSuchMethod(
        Invocation.method(
          #fetchTranslation,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> tafsirDownload(int? i) => (super.noSuchMethod(
        Invocation.method(
          #tafsirDownload,
          [i],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchTafsir({required int? pageNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTafsir,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> closeAndInitializeDatabase({int? pageNumber}) =>
      (super.noSuchMethod(
        Invocation.method(
          #closeAndInitializeDatabase,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.TafsirTableData>> getTafsirOfAyah({
    required int? ayahUniqNumber,
    String? databaseName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTafsirOfAyah,
          [],
          {
            #ayahUniqNumber: ayahUniqNumber,
            #databaseName: databaseName,
          },
        ),
        returnValue: _i5.Future<List<_i2.TafsirTableData>>.value(
            <_i2.TafsirTableData>[]),
      ) as _i5.Future<List<_i2.TafsirTableData>>);

  @override
  _i5.Future<List<_i2.TafsirTableData>> getTafsirOfPage({
    required int? pageNumber,
    String? databaseName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTafsirOfPage,
          [],
          {
            #pageNumber: pageNumber,
            #databaseName: databaseName,
          },
        ),
        returnValue: _i5.Future<List<_i2.TafsirTableData>>.value(
            <_i2.TafsirTableData>[]),
      ) as _i5.Future<List<_i2.TafsirTableData>>);

  @override
  void clearCache([String? key]) => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [key],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [QuranCtrl].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuranCtrl extends _i1.Mock implements _i2.QuranCtrl {
  MockQuranCtrl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i2.QuranPage> get staticPages => (super.noSuchMethod(
        Invocation.getter(#staticPages),
        returnValue: _FakeRxList_6<_i2.QuranPage>(
          this,
          Invocation.getter(#staticPages),
        ),
      ) as _i4.RxList<_i2.QuranPage>);

  @override
  set staticPages(_i4.RxList<_i2.QuranPage>? _staticPages) =>
      super.noSuchMethod(
        Invocation.setter(
          #staticPages,
          _staticPages,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxList<int> get quranStops => (super.noSuchMethod(
        Invocation.getter(#quranStops),
        returnValue: _FakeRxList_6<int>(
          this,
          Invocation.getter(#quranStops),
        ),
      ) as _i4.RxList<int>);

  @override
  set quranStops(_i4.RxList<int>? _quranStops) => super.noSuchMethod(
        Invocation.setter(
          #quranStops,
          _quranStops,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxList<int> get surahsStart => (super.noSuchMethod(
        Invocation.getter(#surahsStart),
        returnValue: _FakeRxList_6<int>(
          this,
          Invocation.getter(#surahsStart),
        ),
      ) as _i4.RxList<int>);

  @override
  set surahsStart(_i4.RxList<int>? _surahsStart) => super.noSuchMethod(
        Invocation.setter(
          #surahsStart,
          _surahsStart,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxList<_i2.Surah> get surahs => (super.noSuchMethod(
        Invocation.getter(#surahs),
        returnValue: _FakeRxList_6<_i2.Surah>(
          this,
          Invocation.getter(#surahs),
        ),
      ) as _i4.RxList<_i2.Surah>);

  @override
  set surahs(_i4.RxList<_i2.Surah>? _surahs) => super.noSuchMethod(
        Invocation.setter(
          #surahs,
          _surahs,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxList<_i2.AyahModel> get ayahs => (super.noSuchMethod(
        Invocation.getter(#ayahs),
        returnValue: _FakeRxList_6<_i2.AyahModel>(
          this,
          Invocation.getter(#ayahs),
        ),
      ) as _i4.RxList<_i2.AyahModel>);

  @override
  int get lastPage => (super.noSuchMethod(
        Invocation.getter(#lastPage),
        returnValue: 0,
      ) as int);

  @override
  set lastPage(int? _lastPage) => super.noSuchMethod(
        Invocation.setter(
          #lastPage,
          _lastPage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set initialPage(int? _initialPage) => super.noSuchMethod(
        Invocation.setter(
          #initialPage,
          _initialPage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxList<_i2.AyahModel> get ayahsList => (super.noSuchMethod(
        Invocation.getter(#ayahsList),
        returnValue: _FakeRxList_6<_i2.AyahModel>(
          this,
          Invocation.getter(#ayahsList),
        ),
      ) as _i4.RxList<_i2.AyahModel>);

  @override
  set ayahsList(_i4.RxList<_i2.AyahModel>? _ayahsList) => super.noSuchMethod(
        Invocation.setter(
          #ayahsList,
          _ayahsList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxList<int> get selectedAyahsByUnequeNumber => (super.noSuchMethod(
        Invocation.getter(#selectedAyahsByUnequeNumber),
        returnValue: _FakeRxList_6<int>(
          this,
          Invocation.getter(#selectedAyahsByUnequeNumber),
        ),
      ) as _i4.RxList<int>);

  @override
  bool get isAyahSelected => (super.noSuchMethod(
        Invocation.getter(#isAyahSelected),
        returnValue: false,
      ) as bool);

  @override
  set isAyahSelected(bool? _isAyahSelected) => super.noSuchMethod(
        Invocation.setter(
          #isAyahSelected,
          _isAyahSelected,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxDouble get scaleFactor => (super.noSuchMethod(
        Invocation.getter(#scaleFactor),
        returnValue: _FakeRxDouble_7(
          this,
          Invocation.getter(#scaleFactor),
        ),
      ) as _i4.RxDouble);

  @override
  set scaleFactor(_i4.RxDouble? _scaleFactor) => super.noSuchMethod(
        Invocation.setter(
          #scaleFactor,
          _scaleFactor,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxDouble get baseScaleFactor => (super.noSuchMethod(
        Invocation.getter(#baseScaleFactor),
        returnValue: _FakeRxDouble_7(
          this,
          Invocation.getter(#baseScaleFactor),
        ),
      ) as _i4.RxDouble);

  @override
  set baseScaleFactor(_i4.RxDouble? _baseScaleFactor) => super.noSuchMethod(
        Invocation.setter(
          #baseScaleFactor,
          _baseScaleFactor,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.RxBool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: _FakeRxBool_8(
          this,
          Invocation.getter(#isLoading),
        ),
      ) as _i4.RxBool);

  @override
  _i4.RxList<_i2.SurahNamesModel> get surahsList => (super.noSuchMethod(
        Invocation.getter(#surahsList),
        returnValue: _FakeRxList_6<_i2.SurahNamesModel>(
          this,
          Invocation.getter(#surahsList),
        ),
      ) as _i4.RxList<_i2.SurahNamesModel>);

  @override
  set surahsList(_i4.RxList<_i2.SurahNamesModel>? _surahsList) =>
      super.noSuchMethod(
        Invocation.setter(
          #surahsList,
          _surahsList,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.QuranState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeQuranState_9(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.QuranState);

  @override
  set state(_i2.QuranState? _state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          _state,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PageController get pageController => (super.noSuchMethod(
        Invocation.getter(#pageController),
        returnValue: _FakePageController_10(
          this,
          Invocation.getter(#pageController),
        ),
      ) as _i3.PageController);

  @override
  _i4.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_11<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_11<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> loadFontsQuran() => (super.noSuchMethod(
        Invocation.method(
          #loadFontsQuran,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i2.AyahModel> getAyahsByPage(int? page) => (super.noSuchMethod(
        Invocation.method(
          #getAyahsByPage,
          [page],
        ),
        returnValue: <_i2.AyahModel>[],
      ) as List<_i2.AyahModel>);

  @override
  _i5.Future<void> loadQuran({dynamic quranPages = 604}) => (super.noSuchMethod(
        Invocation.method(
          #loadQuran,
          [],
          {#quranPages: quranPages},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchSurahs() => (super.noSuchMethod(
        Invocation.method(
          #fetchSurahs,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i2.AyahModel> search(String? searchText) => (super.noSuchMethod(
        Invocation.method(
          #search,
          [searchText],
        ),
        returnValue: <_i2.AyahModel>[],
      ) as List<_i2.AyahModel>);

  @override
  String normalizeText(String? text) => (super.noSuchMethod(
        Invocation.method(
          #normalizeText,
          [text],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #normalizeText,
            [text],
          ),
        ),
      ) as String);

  @override
  List<_i2.AyahModel> searchSurah(String? searchText) => (super.noSuchMethod(
        Invocation.method(
          #searchSurah,
          [searchText],
        ),
        returnValue: <_i2.AyahModel>[],
      ) as List<_i2.AyahModel>);

  @override
  void saveLastPage(int? lastPage) => super.noSuchMethod(
        Invocation.method(
          #saveLastPage,
          [lastPage],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void jumpToPage(int? page) => super.noSuchMethod(
        Invocation.method(
          #jumpToPage,
          [page],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleAyahSelection(int? ayahUnequeNumber) => super.noSuchMethod(
        Invocation.method(
          #toggleAyahSelection,
          [ayahUnequeNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearSelection() => super.noSuchMethod(
        Invocation.method(
          #clearSelection,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Widget textScale(
    dynamic widget1,
    dynamic widget2,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #textScale,
          [
            widget1,
            widget2,
          ],
        ),
        returnValue: _FakeWidget_3(
          this,
          Invocation.method(
            #textScale,
            [
              widget1,
              widget2,
            ],
          ),
        ),
      ) as _i3.Widget);

  @override
  void updateTextScale(_i7.ScaleUpdateDetails? details) => super.noSuchMethod(
        Invocation.method(
          #updateTextScale,
          [details],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Disposer addListener(_i8.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i8.Disposer);

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i9.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Disposer addListenerId(
    Object? key,
    _i8.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i8.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}
