package io.flutter.plugins

import androidx.annotation.Keep
import androidx.annotation.NonNull
import io.flutter.Log
import io.flutter.embedding.engine.FlutterEngine

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
class GeneratedPluginRegistrant {
    companion object {
        @JvmStatic
        fun registerWith(@NonNull flutterEngine: FlutterEngine) {
            try {
                flutterEngine.plugins.add(dev.fluttercommunity.workmanager.WorkmanagerPlugin())
            } catch(e: Exception) {
                Log.e("GeneratedPluginRegistrant", "Error registering plugin workmanager, dev.fluttercommunity.workmanager.WorkmanagerPlugin", e)
            }
            // Add other plugins here as needed
        }
    }
}
